import {Router} from 'express';
const router=Router();
import AuthController from '../controllers/AuthController';
import authMiddleware from '../middleware/AuthMiddleware';
import ChatGroupController from '../controllers/ChatGroupController';
router.post('/auth/login',AuthController.login);
router.post("/chat-group",authMiddleware,ChatGroupController.store);
router.get("/chat-group",authMiddleware,ChatGroupController.index);
router.get("/chat-group/:id",authMiddleware,ChatGroupController.show);
router.put("/chat-group/:id",authMiddleware,ChatGroupController.update);
router.delete("/chat-group/:id",authMiddleware,ChatGroupController.destroy);
export default router;